-- 1. 유저 테이블 (모든 것의 시작!)
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       nickname VARCHAR(50) NOT NULL,
                       university VARCHAR(100)
);

-- 2. 커뮤니티 게시판 (자유/고민)
CREATE TABLE community_posts (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id BIGINT NOT NULL,
                                 category VARCHAR(50),
                                 title VARCHAR(255) NOT NULL,
                                 content TEXT,
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 3. 방 양도 / 룸메이트
CREATE TABLE room_trades (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             title VARCHAR(255) NOT NULL,
                             price INTEGER,
                             location VARCHAR(255),
                             status VARCHAR(20) DEFAULT 'RECRUITING', -- 모집중 상태 기본값
                             CONSTRAINT fk_trades_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 4. 지역/방 후기 (구 Untitled)
CREATE TABLE region_reviews (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                region_name VARCHAR(100),
                                rating INTEGER CHECK (rating >= 1 AND rating <= 5), -- 1~5점 제한
                                content TEXT,
                                CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 5. 공구/대여 (구 Untitled2)
CREATE TABLE group_buys (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL,
                            item_name VARCHAR(255) NOT NULL,
                            target_count INTEGER NOT NULL,
                            current_count INTEGER DEFAULT 1,
                            deadline TIMESTAMP,
                            CONSTRAINT fk_group_buys_user FOREIGN KEY (user_id) REFERENCES users(id)
);