-- V2__add_auth.sql 내용

-- 1. 이미 있는 users 테이블에 'role' 컬럼만 쏙 추가하기
ALTER TABLE users ADD COLUMN role VARCHAR(20) DEFAULT 'USER' NOT NULL;

-- 2. 아예 없던 refresh_tokens 테이블은 새로 만들기
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                token VARCHAR(512) NOT NULL,
                                expiry_date TIMESTAMP NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. 인덱스 추가 (선택)
CREATE INDEX idx_refresh_token_user_id ON refresh_tokens(user_id);