spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LiveAlone
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: http://localhost:9200